sudo: required

services:
  - docker

before_install:
  - docker build -t guygaver/fibonacci-react-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true guygaver/fibonacci-react-client-test npm test

# build the production images and push to docker
after_success: 
  - docker build -t $DOCKER_USER/fibonacci-react-client ./client
  - docker build -t $DOCKER_USER/fibonacci-nginx ./nginx
  - docker build -t $DOCKER_USER/fibonacci-node-server ./server
  - docker build -t $DOCKER_USER/fibonacci-redis-worker ./worker
  
  # login to docker cli by using a pipe operation - pass flag at end to insert password
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

  # push images to docker hub
  - docker push $DOCKER_USER/fibonacci-react-client
  - docker push $DOCKER_USER/fibonacci-nginx
  - docker push $DOCKER_USER/fibonacci-node-server
  - docker push $DOCKER_USER/fibonacci-redis-worker

# deploy instructions for elasticbeanstalk
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Fibonacci Calculator"
  env: "FibonacciCalculator-env"
  bucket_name: "elasticbeanstalk-us-east-1-903881244030"
  bucket_path: "fibonacci" # should be same as app name
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY